# Generated by Django 4.2.30 on 2026-05-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel'), ('sap_procurement', 'SAP Procurement'), ('utility_electricity', 'Utility Electricity'), ('corporate_travel', 'Corporate Travel')], max_length=32)),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.sourcesystem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(blank=True, max_length=128)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('activity_type', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('procurement', 'Procurement'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('ground_transport', 'Ground Transport')], max_length=32)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=16)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('location_code', models.CharField(blank=True, max_length=128)),
                ('activity_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('activity_unit', models.CharField(blank=True, max_length=32)),
                ('emission_kg_co2e', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('emission_unit', models.CharField(default='kgCO2e', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('failed', 'Failed Ingestion')], default='pending', max_length=16)),
                ('review_comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.ingestionbatch')),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.sourcesystem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.tenant')),
            ],
        ),
    ]
